server:
  port: 9000
security:
  sessions: NEVER
spring:
  session:
    store-type: redis
logging:
  level:
    org.springframework:
      security: INFO
      session: INFO
jpa:
  database: mysql
  show-sql: true